### ISSUE TITLE
Dynacache initialization issue when ID is missing

### ISSUE THREAD

**Issue by FcoJavierSainz** [OpenLiberty/openliberty.io#1985]
## Env
WebSphere Application Server Version 20.0.0.12 Liberty - (20.0.0.12-cl201220201111-0736)

```xml
	<feature>distributedMap-1.0</feature>
....
	<distributedMap jndiName="services/cache/topcache">
		<cacheGroup />
	</distributedMap>
```

## Problem
[ERROR   ] DYNA1062E: Dynamic Cache (core cache) failed to initialize. Exception: null

And then 
```
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at com.ibm.ws.cache.CacheServiceImpl.getCacheInstanceConfig(CacheServiceImpl.java:641)
```

## Cause 
Missing ID in the config

```xml
	<distributedMap id="cache" jndiName="services/cache/topcache">
		<cacheGroup />
	</distributedMap>
```

**Comment by FcoJavierSainz** [comment]
moved to https://github.com/OpenLiberty/open-liberty/issues/15337
