### ISSUE TITLE
Initialization Error when web-resource-collection is missing on security-constraint

### ISSUE THREAD

**Issue by FcoJavierSainz** [OpenLiberty/openliberty.io#1986]
## Env
WebSphere Application Server Version 20.0.0.12 Liberty - (20.0.0.12-cl201220201111-0736)
```xml
web.xml
	<security-constraint>
		<user-data-constraint>
			<transport-guarantee>NONE</transport-guarantee>
		</user-data-constraint>
		<auth-constraint>
			<description>
			Unauthenticated users</description>
			<role-name>Unauthenticated</role-name>
		</auth-constraint>
	</security-constraint>
```

## Problem
```
[ERROR  ] CWWKZ0002E: An exception occurred while starting the application TOP6 Web Evaluation Management Territory. The exception message was: com.ibm.ws.container.service.metadata.MetaDataException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

.....
Exception = java.lang.IndexOutOfBoundsException
Source = com.ibm.ws.webcontainer.osgi.WebContainer
probeid = createModuleMetaData
Stack Dump = java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.ibm.ws.webcontainer.security.metadata.SecurityServletConfiguratorHelper.createRoles(SecurityServletConfiguratorHelper.java:566)
	at com.ibm.ws.webcontainer.security.metadata.SecurityServletConfiguratorHelper.createSecurityConstraint(SecurityServletConfiguratorHelper.java:525)
	at com.ibm.ws.webcontainer.security.metadata.SecurityServletConfiguratorHelper.processSecurityConstraints(SecurityServletConfiguratorHelper.java:290)
	at com.ibm.ws.webcontainer.security.metadata.SecurityServletConfiguratorHelper.configureSecurity(SecurityServletConfiguratorHelper.java:257)
	at com.ibm.ws.webcontainer.security.metadata.SecurityServletConfiguratorHelper.configureFromWebApp(SecurityServletConfiguratorHelper.java:101)
```

## Cause
Missing the `web-resource-collection` inside a `security-constraint` directive

**Comment by FcoJavierSainz** [comment]
moved to https://github.com/OpenLiberty/open-liberty/issues/15338
