### ISSUE TITLE
Docs features don't scroll to the right page in the TOC

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#3471]
Visit https://openliberty.io/docs/latest/reference/feature/feature-overview.html and see that the TOC isn't scrolled to because of a javascript error:
```
jquery.min.js:2 Uncaught TypeError: n.parent is not a function
    at Object.a [as activateCurrentPath] (01-nav.js:79:28)
    at selectTOC (05-features.js:94:16)
    at HTMLDocument.<anonymous> (05-features.js:104:3)
    at l (jquery.min.js:2:29375)
    at c (jquery.min.js:2:29677)
```

**Comment by steven1046** [comment]
I don't think it's fixed yet on staging: https://staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/kernel.html
